shared: &shared
  adapter: sqlite3
  pool: 50
  timeout: 5000

development:
  <<: *shared
  database: games/rbpkr_development.sqlite3

test:
  <<: *shared
  database: games/rbpkr_test.sqlite3

production:
  <<: *shared
  database: games/rbpkr_production.sqlite3
